# Using _EGObox_ optimizer _Egor_

_Last Update: 30/03/2026_

## Installation

In [1]:
# %pip install egobox

We import _egobox_ as _egx_ for short.

In [2]:
import numpy as np
import egobox as egx

## Example 1 : Continuous optimization

### Test functions

In [3]:
xspecs_xsinx = [[0., 25.]]
n_cstr_xsinx = 0

def xsinx(x: np.ndarray) -> np.ndarray:
    x = np.atleast_2d(x)
    y = (x - 3.5) * np.sin((x - 3.5) / (np.pi))
    return y

In [4]:
xspecs_g24 = [[0., 3.], [0., 4.]]
n_cstr_g24 = 2

# Objective
def G24(point):
    """
    Function g24
    1 global optimum y_opt = -5.5080 at x_opt =(2.3295, 3.1785)
    """
    p = np.atleast_2d(point)
    return - p[:, 0] - p[:, 1]

# Constraints < 0
def G24_c1(point):
    p = np.atleast_2d(point)
    return (- 2.0 * p[:, 0] ** 4.0
            + 8.0 * p[:, 0] ** 3.0 
            - 8.0 * p[:, 0] ** 2.0 
            + p[:, 1] - 2.0)

def G24_c2(point):
    p = np.atleast_2d(point)
    return (-4.0 * p[:, 0] ** 4.0
            + 32.0 * p[:, 0] ** 3.0
            - 88.0 * p[:, 0] ** 2.0
            + 96.0 * p[:, 0]
            + p[:, 1] - 36.0)

# Grouped evaluation
def g24(point):
    p = np.atleast_2d(point)
    return np.array([G24(p), G24_c1(p), G24_c2(p)]).T


### Utility function

Simple utility function used below to display Egor minimize output.

In [5]:
def print_output(optim):
    result = optim.result
    status = optim.status

    print(f"Optimization {status.info.fname}({result.x_opt})={result.y_opt}")
    print("Optimization history: ")
    print(f"x: {result.x_doe}")
    print(f"y: {result.y_doe}")
    print("Optimization run status: ")
    print(f"  minimize: {status.info.fname}, run={status.info.num}")
    print(f"  exit status: {status.exit}")
    print(f"  init_doe_size: {status.init_doe_size}")
    print(f"  best_iter: {status.best_iter}")
    print(f"  total_iters: {status.total_iters}")
    print(f"  elapsed_time: {status.elapsed_time}ms")

### Continuous optimization

In [6]:
# Unconstrained 1D function
egor = egx.Egor(xspecs_xsinx)   # see help(egor) for options
optim = egor.minimize(xsinx, max_iters=30, run_info=egx.RunInfo(fname="xsinx", num=13))
print_output(optim)

Optimization xsinx([18.91820911])=[-15.12486354]
Optimization history: 
x: [[ 5.93683852]
 [22.8560293 ]
 [ 0.70229159]
 [15.67010537]
 [12.76165739]
 [16.19250486]
 [16.98043916]
 [18.725782  ]
 [ 5.93661189]
 [18.91820911]
 [15.4161151 ]
 [16.94946794]
 [16.60393313]
 [15.09936277]
 [14.63503806]
 [13.75419059]
 [17.23380571]
 [17.38445498]
 [12.36421339]
 [11.76000254]
 [11.18444532]
 [17.56992944]
 [10.52393284]
 [17.68837624]
 [17.78939417]
 [ 9.81296624]
 [ 9.04742989]
 [17.87681473]
 [ 8.20650057]
 [ 7.18249628]
 [17.95574332]
 [ 5.59810854]
 [18.00534728]
 [ 4.94878601]
 [ 4.39277126]]
y: [[  1.70626076]
 [ -2.35500227]
 [  2.17496765]
 [ -8.13645903]
 [  1.78110934]
 [ -9.93098627]
 [-12.30095629]
 [-15.08902895]
 [  1.70597658]
 [-15.12486354]
 [ -7.22497749]
 [-12.21786083]
 [-11.23074114]
 [ -6.06876291]
 [ -4.3648884 ]
 [ -1.25216028]
 [-12.94401995]
 [-13.29340599]
 [  2.78860303]
 [  4.04929073]
 [  4.92429794]
 [-13.68715783]
 [  5.52728993]
 [-13.91647251]
 [-14.097815

In [7]:
# Constrained 2D function
egor = egx.Egor(xspecs_g24, 
                n_doe=5, 
                n_cstr=n_cstr_g24, 
                cstr_tol=[1e-3, 1e-3],
                infill_strategy=egx.InfillStrategy.WB2,
                target=-5.5,
                trego=False,
            )   

In [8]:
optim = egor.minimize(g24, max_iters=30, run_info=egx.RunInfo(fname="g24"))
print_output(optim)

Optimization g24([2.32953676 3.1787445 ])=[-5.50828125e+00  1.16230275e-04  3.29242113e-04]
Optimization history: 
x: [[0.67768414 0.49030276]
 [2.81834782 0.87867323]
 [0.31598474 2.45150564]
 [1.80406067 1.99283847]
 [1.45407308 3.72056128]
 [3.         4.        ]
 [2.9999998  3.56396548]
 [2.51239838 4.        ]
 [2.29418227 3.9999986 ]
 [2.39641616 2.53174074]
 [2.33015124 3.1893045 ]
 [2.32953676 3.1787445 ]]
y: [[-1.16798690e+00 -3.11573241e+00 -1.75082143e+00]
 [-3.69702105e+00 -1.17601853e+01  4.42262781e-01]
 [-2.76749038e+00 -1.14804395e-01 -1.10307183e+01]
 [-3.79689914e+00 -2.57066856e-01 -1.70591962e+00]
 [-5.17463435e+00  4.60268379e-01  1.74954861e+00]
 [-7.00000000e+00 -1.60000000e+01  4.00000000e+00]
 [-6.56396528e+00 -1.64360251e+01  3.56396548e+00]
 [-6.51239838e+00 -1.31453411e+00  1.82468235e+00]
 [-6.29418087e+00  1.08899766e+00  6.62385362e-01]
 [-4.92815690e+00 -1.27317597e+00 -3.09872282e-01]
 [-5.51945574e+00  5.65241757e-03  1.37793503e-02]
 [-5.50828125e+00

### Egor as a service: ask-and-tell interface

When the user needs to be in control of the optimization loop, `Egor` can be used as a service. 

For instance with the `xsinx` objective function, we can do:

In [9]:
xlimits = [[0.0, 25.0]]
egor = egx.Egor(xlimits)

# initial doe
x_doe = egx.lhs(xlimits, 3, seed=42)
y_doe = xsinx(x_doe)
for _ in range(10): # run for 10 iterations
    x = egor.suggest(x_doe, y_doe, seed=42)  # ask for best location
    x_doe = np.concatenate((x_doe, x))
    y_doe = np.concatenate((y_doe, xsinx(x))) 
result = egor.get_result(x_doe, y_doe)
print(f"Optimization f={result.y_opt} at {result.x_opt}")

Optimization f=[-15.12500826] at [18.92451016]


## Example 2 : Mixed-integer optimization

### Test function

In [10]:
xspecs_mixint_xsinx = [egx.XSpec(egx.XType.INT, [0, 25])]
n_cstr_mixint_xsinx = 0

def mixint_xsinx(x: np.ndarray) -> np.ndarray:
    x = np.atleast_2d(x)
    if (np.abs(np.linalg.norm(np.floor(x))-np.linalg.norm(x))< 1e-8):
        y = (x - 3.5) * np.sin((x - 3.5) / (np.pi))
    else:
        raise ValueError(f"Bad input: mixint_xsinx accepts integer only, got {x}")
    return y

### Mixed-integer optimization with _Egor_

In [11]:
egor = egx.Egor(xspecs_mixint_xsinx, 
                     n_doe=3, 
                     infill_strategy=egx.InfillStrategy.EI,
                     target=-15.12,
                    )  # see help(egor) for options
optim = egor.minimize(mixint_xsinx, max_iters=30)
print_output(optim)

Optimization objective_function([19.])=[-15.12161154]
Optimization history: 
x: [[ 3.]
 [19.]
 [14.]]
y: [[  0.07924194]
 [-15.12161154]
 [ -2.09283123]]
Optimization run status: 
  minimize: objective_function, run=1
  exit status: ExitStatus.TARGET_COST_REACHED
  init_doe_size: 3
  best_iter: 0
  total_iters: 0
  elapsed_time: 0.0ms


## Example 3 : More mixed-integer optimization

In the following example we see we can have other special integer type cases, where a component of x can take one value out of a list of ordered values (ORD type) or being like an enum value (ENUM type). Those types differ by the processing related to the continuous relaxation made behind the scene:
* For INT type, resulting float is rounded to the closest int value,
* For ORD type, resulting float is cast to closest value among the given valid ones,
* For ENUM type, one hot encoding is performed to give the resulting value.  

### Test function

In [12]:
# Objective function which takes [FLOAT, ENUM1, ENUM2, ORD] as input
# Note that ENUM values are passed as indice value eg either 0, 1 or 2 for a 3-sized enum  
def mixobj(X):
    # float
    x1 = X[:, 0]
    #  ENUM 1
    c1 = X[:, 1]
    x2 = c1 == 0
    x3 = c1 == 1
    x4 = c1 == 2
    #  ENUM 2
    c2 = X[:, 2]
    x5 = c2 == 0
    x6 = c2 == 1
    # int
    i = X[:, 3]

    y = (x2 + 2 * x3 + 3 * x4) * x5 * x1 + (x2 + 2 * x3 + 3 * x4) * x6 * 0.95 * x1 + i
    return y.reshape(-1, 1)

### Mixed-integer optimization with _Egor_

In [13]:
xtypes = [
    egx.XSpec(egx.XType.FLOAT, [-5.0, 5.0]),
    egx.XSpec(egx.XType.ENUM, tags=["blue", "red", "green"]),
    egx.XSpec(egx.XType.ENUM, xlimits=[2]),
    egx.XSpec(egx.XType.ORD, [0, 2, 3]),
]
egor = egx.Egor(xtypes)
optim = egor.minimize(mixobj, max_iters=10, seed=42)
print_output(optim)

Optimization objective_function([-5.  2.  1.  0.])=[-14.25]
Optimization history: 
x: [[ 1.62883164e+00  1.00000000e+00  0.00000000e+00  3.00000000e+00]
 [-3.36198576e+00  1.00000000e+00  0.00000000e+00  2.00000000e+00]
 [ 4.03379217e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.36985740e-05  0.00000000e+00  0.00000000e+00  3.00000000e+00]
 [-8.66923347e-01  2.00000000e+00  1.00000000e+00  2.00000000e+00]
 [ 2.60951201e+00  0.00000000e+00  0.00000000e+00  2.00000000e+00]
 [-2.42178777e+00  2.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-4.89280551e+00  0.00000000e+00  0.00000000e+00  2.00000000e+00]
 [-3.76155831e+00  2.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-4.64338307e+00  2.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-5.00000000e+00  2.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-5.00000000e+00  2.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-5.00000000e+00  2.00000000e+00  1.00000000e+00  2.00000000e+00]
 [-5.00000000e+00  2.00000000e+00  1.000000

Note that `x_opt` result contains indices for corresponding optional tags list hence the second component should be read as 0="red", 1="green", 2="blue", while the third component was unamed 0 correspond to first enum value and 1 to the second one.

## Usage

In [14]:
help(egor)

Help on Egor in module builtins object:

class Egor(object)
 |  Egor(xspecs, gp_config=Ellipsis, n_cstr=0, cstr_tol=None, n_start=20, n_doe=0, doe=None, infill_strategy=Ellipsis, cstr_infill=False, cstr_strategy=Ellipsis, qei_config=Ellipsis, infill_optimizer=Ellipsis, trego=None, coego_n_coop=0, target=Ellipsis, failsafe_strategy=Ellipsis)
 |
 |  Optimizer constructor
 |
 |  # Parameters
 |
 |      xspecs (list(XSpec)) where XSpec(xtype=FLOAT|INT|ORD|ENUM, xlimits=[<f(xtype)>] or tags=[strings]):
 |          Specifications of the nx components of the input x (eg. len(xspecs) == nx)
 |          Depending on the x type we get the following for xlimits:
 |          * when FLOAT: xlimits is [float lower_bound, float upper_bound],
 |          * when INT: xlimits is [int lower_bound, int upper_bound],
 |          * when ORD: xlimits is [float_1, float_2, ..., float_n],
 |          * when ENUM: xlimits is just the int size of the enumeration otherwise a list of tags is specified
 |          

In [15]:
help(egx.GpConfig)

Help on class GpConfig in module builtins:

class GpConfig(object)
 |  GpConfig(regr_spec=Ellipsis, corr_spec=Ellipsis, kpls_dim=Ellipsis, n_clusters=Ellipsis, recombination=Ellipsis, theta_init=Ellipsis, theta_bounds=Ellipsis, n_start=Ellipsis, max_eval=Ellipsis)
 |
 |  GP configuration used by `Egor` and `GpMix`
 |
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs)
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  corr_spec
 |      (CorrelationSpec flags, an int in [1, 15])
 |      Specification of correlation models used in mixture.
 |      Can be CorrelationSpec.SQUARED_EXPONENTIAL (1), CorrelationSpec.ABSOLUTE_EXPONENTIAL (2),
 |      CorrelationSpec.MATERN32 (4), CorrelationSpec.MATERN52 (8) or
 |      any bit-wise union of these values (e.g. CorrelationSpec.MATERN32 | CorrelationSpec.MATERN52)
 |
 |  kpls_dim
 |      