# Using _EGObox_ optimizer _Egor_

_Last Update: 17/03/2026_

## Installation

In [16]:
# %pip install egobox

We import _egobox_ as _egx_ for short.

In [17]:
import numpy as np
import egobox as egx

## Example 1 : Continuous optimization

### Test functions

In [18]:
xspecs_xsinx = [[0., 25.]]
n_cstr_xsinx = 0

def xsinx(x: np.ndarray) -> np.ndarray:
    x = np.atleast_2d(x)
    y = (x - 3.5) * np.sin((x - 3.5) / (np.pi))
    return y

In [19]:
xspecs_g24 = [[0., 3.], [0., 4.]]
n_cstr_g24 = 2

# Objective
def G24(point):
    """
    Function g24
    1 global optimum y_opt = -5.5080 at x_opt =(2.3295, 3.1785)
    """
    p = np.atleast_2d(point)
    return - p[:, 0] - p[:, 1]

# Constraints < 0
def G24_c1(point):
    p = np.atleast_2d(point)
    return (- 2.0 * p[:, 0] ** 4.0
            + 8.0 * p[:, 0] ** 3.0 
            - 8.0 * p[:, 0] ** 2.0 
            + p[:, 1] - 2.0)

def G24_c2(point):
    p = np.atleast_2d(point)
    return (-4.0 * p[:, 0] ** 4.0
            + 32.0 * p[:, 0] ** 3.0
            - 88.0 * p[:, 0] ** 2.0
            + 96.0 * p[:, 0]
            + p[:, 1] - 36.0)

# Grouped evaluation
def g24(point):
    p = np.atleast_2d(point)
    return np.array([G24(p), G24_c1(p), G24_c2(p)]).T


### Utility function

Simple utility function used below to display Egor minimize output.

In [20]:
def print_output(result, status):
    print(f"Optimization {status.info.fname}({result.x_opt})={result.y_opt}")
    print("Optimization history: ")
    print(f"x: {result.x_doe}")
    print(f"y: {result.y_doe}")
    print("Optimization run status: ")
    print(f"  minimize: {status.info.fname}, run={status.info.num}")
    print(f"  exit status: {status.exit}")
    print(f"  init_doe_size: {status.init_doe_size}")
    print(f"  best_iter: {status.best_iter}")
    print(f"  total_iters: {status.total_iters}")
    print(f"  elapsed_time: {status.elapsed_time}ms")

### Continuous optimization

In [21]:
# Unconstrained 1D function
egor = egx.Egor(xspecs_xsinx)   # see help(egor) for options
result, status = egor.minimize(xsinx, max_iters=30, run_info=egx.RunInfo(fname="xsinx", num=13))
print_output(result, status)

Optimization xsinx([18.84599627])=[-15.11852307]
Optimization history: 
x: [[1.96995074e+01]
 [2.36707413e+01]
 [7.88384306e+00]
 [1.13061245e+01]
 [3.72315200e+00]
 [1.88459963e+01]
 [1.90870813e+01]
 [2.49495611e-13]]
y: [[-14.6282964 ]
 [  2.76196944]
 [  4.3165995 ]
 [  4.76646934]
 [  0.01583749]
 [-15.11852307]
 [-15.10585406]
 [  3.14127616]]
Optimization run status: 
  minimize: xsinx, run=13
  exit status: ExitStatus.SOLVER_CONVERGED
  init_doe_size: 5
  best_iter: 0
  total_iters: 4
  elapsed_time: 20.0ms


In [22]:
# Constrained 2D function
egor = egx.Egor(xspecs_g24, 
                n_doe=5, 
                n_cstr=n_cstr_g24, 
                cstr_tol=[1e-3, 1e-3],
                infill_strategy=egx.InfillStrategy.WB2,
                target=-5.5,
                trego=False,
            )   

In [23]:
result, status = egor.minimize(g24, max_iters=30, run_info=egx.RunInfo(fname="g24"))
print_output(result, status)

Optimization g24([2.32952791 3.17884859])=[-5.50837651e+00  2.92526086e-04  3.91780848e-04]
Optimization history: 
x: [[1.15519944 1.18027221]
 [2.22408506 0.32859588]
 [1.25929545 3.79983532]
 [2.68957893 1.92582036]
 [0.57653208 2.42752559]
 [3.         4.        ]
 [3.         3.37218543]
 [2.24425499 3.99998957]
 [2.11620602 3.84032657]
 [2.35859916 3.03354085]
 [2.32957852 3.18384093]
 [2.32947015 3.17942964]
 [2.32952791 3.17884859]]
y: [[-2.33547165e+00 -2.72454068e+00  8.52373924e-01]
 [-2.55268094e+00 -2.16817778e+00 -3.27977705e+00]
 [-5.05913077e+00  5.97309785e-02  2.98494361e+00]
 [-4.61539928e+00 -6.95383284e+00  8.25499489e-01]
 [-3.00405766e+00 -9.19489054e-01 -1.78532039e+00]
 [-7.00000000e+00 -1.60000000e+01  4.00000000e+00]
 [-6.37218543e+00 -1.66278146e+01  3.37218543e+00]
 [-6.24424456e+00  1.39900781e+00  4.63036070e-01]
 [-5.95653259e+00  1.71937733e+00 -5.23721297e-02]
 [-5.39214000e+00 -3.97186247e-01 -3.85731774e-03]
 [-5.51341946e+00  4.87161240e-03  5.621991

### Egor as a service: ask-and-tell interface

When the user needs to be in control of the optimization loop, `Egor` can be used as a service. 

For instance with the `xsinx` objective function, we can do:

In [24]:
xlimits = [[0.0, 25.0]]
egor = egx.Egor(xlimits, seed=42) 

# initial doe
x_doe = egx.lhs(xlimits, 3, seed=42)
y_doe = xsinx(x_doe)
for _ in range(10): # run for 10 iterations
    x = egor.suggest(x_doe, y_doe)  # ask for best location
    x_doe = np.concatenate((x_doe, x))
    y_doe = np.concatenate((y_doe, xsinx(x))) 
result = egor.get_result(x_doe, y_doe)
print(f"Optimization f={result.y_opt} at {result.x_opt}")

Optimization f=[-15.12500826] at [18.92451016]


## Example 2 : Mixed-integer optimization

### Test function

In [25]:
xspecs_mixint_xsinx = [egx.XSpec(egx.XType.INT, [0, 25])]
n_cstr_mixint_xsinx = 0

def mixint_xsinx(x: np.ndarray) -> np.ndarray:
    x = np.atleast_2d(x)
    if (np.abs(np.linalg.norm(np.floor(x))-np.linalg.norm(x))< 1e-8):
        y = (x - 3.5) * np.sin((x - 3.5) / (np.pi))
    else:
        raise ValueError(f"Bad input: mixint_xsinx accepts integer only, got {x}")
    return y

### Mixed-integer optimization with _Egor_

In [26]:
egor = egx.Egor(xspecs_mixint_xsinx, 
                     n_doe=3, 
                     infill_strategy=egx.InfillStrategy.EI,
                     target=-15.12,
                    )  # see help(egor) for options
result, status = egor.minimize(mixint_xsinx, max_iters=30)
print_output(result, status)

Optimization objective_function([19.])=[-15.12161154]
Optimization history: 
x: [[10.]
 [25.]
 [ 6.]
 [ 3.]
 [ 1.]
 [17.]
 [18.]
 [19.]]
y: [[  5.70983099]
 [ 11.42919546]
 [  1.78601478]
 [  0.07924194]
 [  1.78601478]
 [-12.35295142]
 [-14.43198471]
 [-15.12161154]]
Optimization run status: 
  minimize: objective_function, run=1
  exit status: ExitStatus.TARGET_COST_REACHED
  init_doe_size: 3
  best_iter: 5
  total_iters: 5
  elapsed_time: 44.0ms


## Example 3 : More mixed-integer optimization

In the following example we see we can have other special integer type cases, where a component of x can take one value out of a list of ordered values (ORD type) or being like an enum value (ENUM type). Those types differ by the processing related to the continuous relaxation made behind the scene:
* For INT type, resulting float is rounded to the closest int value,
* For ORD type, resulting float is cast to closest value among the given valid ones,
* For ENUM type, one hot encoding is performed to give the resulting value.  

### Test function

In [27]:
# Objective function which takes [FLOAT, ENUM1, ENUM2, ORD] as input
# Note that ENUM values are passed as indice value eg either 0, 1 or 2 for a 3-sized enum  
def mixobj(X):
    # float
    x1 = X[:, 0]
    #  ENUM 1
    c1 = X[:, 1]
    x2 = c1 == 0
    x3 = c1 == 1
    x4 = c1 == 2
    #  ENUM 2
    c2 = X[:, 2]
    x5 = c2 == 0
    x6 = c2 == 1
    # int
    i = X[:, 3]

    y = (x2 + 2 * x3 + 3 * x4) * x5 * x1 + (x2 + 2 * x3 + 3 * x4) * x6 * 0.95 * x1 + i
    return y.reshape(-1, 1)

### Mixed-integer optimization with _Egor_

In [28]:
xtypes = [
    egx.XSpec(egx.XType.FLOAT, [-5.0, 5.0]),
    egx.XSpec(egx.XType.ENUM, tags=["blue", "red", "green"]),
    egx.XSpec(egx.XType.ENUM, xlimits=[2]),
    egx.XSpec(egx.XType.ORD, [0, 2, 3]),
]
egor = egx.Egor(xtypes, seed=42)
result, status = egor.minimize(mixobj, max_iters=10)
print_output(result, status)

Optimization objective_function([-5.  2.  1.  0.])=[-14.25]
Optimization history: 
x: [[ 1.62883164e+00  1.00000000e+00  0.00000000e+00  3.00000000e+00]
 [-3.36198576e+00  1.00000000e+00  0.00000000e+00  2.00000000e+00]
 [ 4.03379217e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.36985740e-05  0.00000000e+00  0.00000000e+00  3.00000000e+00]
 [-8.66923347e-01  2.00000000e+00  1.00000000e+00  2.00000000e+00]
 [ 2.60951201e+00  0.00000000e+00  0.00000000e+00  2.00000000e+00]
 [-2.42178777e+00  2.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-4.89280551e+00  0.00000000e+00  0.00000000e+00  2.00000000e+00]
 [-3.76155831e+00  2.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-4.64338307e+00  2.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-5.00000000e+00  2.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-5.00000000e+00  2.00000000e+00  1.00000000e+00  3.00000000e+00]
 [-5.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.00000000e+00  1.00000000e+00  0.000000

Note that `x_opt` result contains indices for corresponding optional tags list hence the second component should be read as 0="red", 1="green", 2="blue", while the third component was unamed 0 correspond to first enum value and 1 to the second one.

## Usage

In [29]:
help(egor)

Help on Egor in module builtins object:

class Egor(object)
 |  Egor(xspecs, gp_config=Ellipsis, n_cstr=0, cstr_tol=None, n_start=20, n_doe=0, doe=None, infill_strategy=Ellipsis, cstr_infill=False, cstr_strategy=Ellipsis, qei_config=Ellipsis, infill_optimizer=Ellipsis, trego=None, coego_n_coop=0, target=Ellipsis, outdir=None, warm_start=False, hot_start=None, failsafe_strategy=Ellipsis, seed=None, verbose=None)
 |
 |  Optimizer constructor
 |
 |  # Parameters
 |
 |      xspecs (list(XSpec)) where XSpec(xtype=FLOAT|INT|ORD|ENUM, xlimits=[<f(xtype)>] or tags=[strings]):
 |          Specifications of the nx components of the input x (eg. len(xspecs) == nx)
 |          Depending on the x type we get the following for xlimits:
 |          * when FLOAT: xlimits is [float lower_bound, float upper_bound],
 |          * when INT: xlimits is [int lower_bound, int upper_bound],
 |          * when ORD: xlimits is [float_1, float_2, ..., float_n],
 |          * when ENUM: xlimits is just the int si

In [30]:
help(egx.GpConfig)

Help on class GpConfig in module builtins:

class GpConfig(object)
 |  GpConfig(regr_spec=Ellipsis, corr_spec=Ellipsis, kpls_dim=Ellipsis, n_clusters=Ellipsis, recombination=Ellipsis, theta_init=Ellipsis, theta_bounds=Ellipsis, n_start=Ellipsis, max_eval=Ellipsis)
 |
 |  GP configuration used by `Egor` and `GpMix`
 |
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs)
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  corr_spec
 |      (CorrelationSpec flags, an int in [1, 15])
 |      Specification of correlation models used in mixture.
 |      Can be CorrelationSpec.SQUARED_EXPONENTIAL (1), CorrelationSpec.ABSOLUTE_EXPONENTIAL (2),
 |      CorrelationSpec.MATERN32 (4), CorrelationSpec.MATERN52 (8) or
 |      any bit-wise union of these values (e.g. CorrelationSpec.MATERN32 | CorrelationSpec.MATERN52)
 |
 |  kpls_dim
 |      